import { Product } from './types';


export const products: Product[] = [
  {
    id: 1,
    category: 'Female',
    title: 'Elegant Embroidered   Shalwar Kameez Female Rs $50',
    price: 'RS:$50',
    image: '/female1.jpeg',  // Corrected path (inside the public folder)
    quantity: "1",
  },
  {
    id: 2,
    category: 'Female',
    title: 'Traditional Cotton Shalwar Kameez Rs $45',
    price: 'RS:$45',
    image: '/female2.jpeg', // Correct path if inside /public/images
     quantity: "1",
  },
  {
    id: 3,
    category: 'Female',
    title: 'Festive Silk Shalwar Kameez Rs $60 ',
    price: 'RS:$60',
    image: '/female3.jpeg',
    quantity: "1",
  },
  {
    id: 4,
    category: 'Female',
    title: 'Designer Shalwar Kameez  Dupatta Rs $70',
    price: 'RS:$70',
    image: '/female4.jpeg',
    quantity: "1",
  },
  {
    id: 5,
    category: 'Female',
    title: 'Printed Shalwar Kameez  Dupatta Rs $65',
    price: 'RS:$65',
    image: '/female5.jpeg',
    quantity: "1",
  },
  {
    id: 6,
    category: 'Female',
    title: 'Chiffon Shalwar Kameez  Dupatta Rs $80',
    price: 'RS:$80',
    image: '/female6.jpeg',
    quantity: "1",
  },
  {
    id: 7,
    category: 'Male',
    title: 'Classic White Shalwar Kameez Rs $40',
    price: 'RS:$40',
    image: '/male1.jpeg',
    quantity: "1",
  },
  {
    id: 8,
    category: 'Male',
    title: 'Casual Black Shalwar Kameez Rs $45',
    price: 'RS:$45',
    image: '/male2.jpeg',
    quantity: "1",
  },
  {
    id: 9,
    category: 'Male',
    title: 'Formal Grey Shalwar Kameez Rs $50',
    price: 'RS:$50',
    image: '/male3.jpeg',
    quantity: "1",
  },
  {
    id: 10,
    category: 'Female',
    title: 'Summer Lawn Shalwar Kameez Rs $35',
    price: 'RS:$35',
    image: '/female10.jpeg',
    quantity: "1",
  },
  {
    id: 11,
    category: 'Female',
    title: 'Embroidered Shalwar Kameez  Dupatta Rs $75',
    price: 'RS:$75',
    image: '/female11.jpeg',
    quantity: "1",
  },
  {
    id: 12,
    category: 'Male',
    title: 'Winter Woolen Shalwar Kameez Rs $55',
    price: 'RS:$55',
    image: '/male4.jpeg',
    quantity: "1",
  },
  {
    id: 13,
    category: 'Female',
    title: 'Party Wear Shalwar Kameez Rs $85',
    price: 'RS:$85',
    image: '/female12.jpeg',
    quantity: "1",
  },
  {
    id: 14,
    category: 'Female',
    title: 'Velvet Shalwar Kameez  Dupatta Rs $90',
    price: 'RS:$90',
    image: '/female11.jpeg',
    quantity: "1",
  },
  {
    id: 15,
    category: 'Female',
    title: 'Premium Embroidered Shalwar Kameez Rs $65',
    price: 'RS:$65',
    image: '/female5.jpeg',
    quantity: "1",
  },
  {
    id: 16,
    category: 'Female',
    title: 'Casual Floral Shalwar Kameez Rs $40',
    price: 'RS:$40',
    image: '/female13.jpeg',
    quantity: "1",
  },
];

